# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab5():
  def setup_method(self, method):
    self.driver = webdriver.Edge()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab5(self):
    self.driver.get("https://demo.opencart.com/")
    self.driver.set_window_size(1552, 832)
    assert self.driver.title == "Your Store"
    self.driver.find_element(By.CSS_SELECTOR, ".show > .d-none").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h1")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".alert")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "input-firstname").click()
    self.driver.find_element(By.ID, "input-firstname").send_keys("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR")
    self.driver.find_element(By.NAME, "agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    elements = self.driver.find_elements(By.ID, "error-firstname")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "input-lastname").click()
    self.driver.find_element(By.ID, "input-lastname").send_keys("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR")
    self.driver.find_element(By.NAME, "agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    elements = self.driver.find_elements(By.ID, "error-lastname")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("Rohit@1344.com")
    self.driver.find_element(By.CSS_SELECTOR, "fieldset:nth-child(2) > legend").click()
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("Rohit@123")
    self.driver.find_element(By.ID, "input-newsletter").click()
    self.driver.find_element(By.NAME, "agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "input-firstname").click()
    self.driver.find_element(By.ID, "input-firstname").send_keys("Rohit")
    self.driver.find_element(By.ID, "input-lastname").click()
    self.driver.find_element(By.ID, "input-lastname").send_keys("v h")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h1")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Continue").click()
    self.driver.find_element(By.LINK_TEXT, "View your order history").click()
  
