# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDay16Q1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_day16Q1(self):
    self.driver.get("https://tutorialsninja.com/demo/index.php?route=account/register")
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#content > h1")))
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'firstname\']").send_keys("Akash")
    self.driver.find_element(By.NAME, "lastname").send_keys("kumar")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'email\']").send_keys("aka123@1234.com")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'telephone\']").send_keys("8745963214")
    self.driver.find_element(By.XPATH, "//input[@name=\'password\']").send_keys("8745")
    self.driver.find_element(By.XPATH, "//input[@name=\'confirm\']").send_keys("8745")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'newsletter\'][value=\'1\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'agree\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\'submit\']").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#content h1").text == \
           "Your Account Has Been Created!"
  
