# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab1():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab1(self):
    # Test name: lab_1
    # Step # | name | target | value
    # 1 | open | https://www.google.com/ | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | mouseOver | css=.gb_B | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".gb_B")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | mouseOut | css=.gb_B | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 5 | click | id=APjFqb | 
    self.driver.find_element(By.ID, "APjFqb").click()
    # 6 | type | id=APjFqb | testing mwthods
    self.driver.find_element(By.ID, "APjFqb").send_keys("testing mwthods")
    # 7 | click | css=#jZ2SBf > .wM6W7d > span | 
    self.driver.find_element(By.CSS_SELECTOR, "#jZ2SBf > .wM6W7d > span").click()
    # 8 | click | css=.in7vHe > .niO4u | 
    self.driver.find_element(By.CSS_SELECTOR, ".in7vHe > .niO4u").click()
    # 9 | verifyElementPresent | css=.Fzsovc:nth-child(4) | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".Fzsovc:nth-child(4)")
    assert len(elements) > 0
  
