# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab2():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab2(self):
    # Test name: lab_2
    # Step # | name | target | value
    # 1 | open | https://demo.opencart.com/ | 
    self.driver.get("https://demo.opencart.com/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | linkText=Tablets | 
    self.driver.find_element(By.LINK_TEXT, "Tablets").click()
    # 4 | verifyElementPresent | css=h2 | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h2")
    assert len(elements) > 0
  
