# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDay15Q2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_day15Q2(self):
    self.driver.get("https://practice.expandtesting.com/login")
    self.driver.set_window_size(1536, 816)
    self.driver.execute_script("window.scrollTo(0,94.4000015258789)")
    self.driver.execute_script("window.scrollTo(0,268.79998779296875)")
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(4) > li:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(4) > li:nth-child(1)").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("practice")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("SuperSecretPassword!")
    self.driver.find_element(By.ID, "submit-login").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "b")
    assert len(elements) > 0
  
