# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab3():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab3(self):
    # Test name: lab_3
    # Step # | name | target | value
    # 1 | open | https://demo.opencart.com/ | 
    self.driver.get("https://demo.opencart.com/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | linkText=Desktops | 
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    # 4 | click | linkText=Mac (1) | 
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    # 5 | click | css=.col-lg-4 .input-group-text | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4 .input-group-text").click()
    # 6 | click | id=input-sort | 
    self.driver.find_element(By.ID, "input-sort").click()
    # 7 | select | id=input-sort | label=Name (A - Z)
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    # 8 | click | css=.image .img-fluid | 
    self.driver.find_element(By.CSS_SELECTOR, ".image .img-fluid").click()
    # 9 | click | id=button-cart | 
    self.driver.find_element(By.ID, "button-cart").click()
    # 10 | mouseOver | id=button-cart | 
    element = self.driver.find_element(By.ID, "button-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | mouseOut | id=button-cart | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
